sudo: required
install:
- npm install
script:
- npm run build
deploy:
  provider: firebase
  token:
    secure: "mJJxqPzDbTo/ekyMZMbXUleMtVVdGo5aIPFhiQVpfsX1FMGzSQJixISxDBOwbjSIjba/ZMtYmwtHzVqWXadyQnWPf0HD5fsyxpybm8/CdnR3kKq3XUTt8hmpRxdxBBHpfn501BcdE+P+iNcJtpl3CFh2G5+l9p6D45bQnXJEHGJ/p7z9dykAzWU3grEmVCAj7BBNWkieKGc2q+ZNoAZKGSvNXxJJ9kJufYYwWhu01MPzNKcOh5tL3AzZHHWJk6Ty7wMUfW7XlsfpnsPFbgndJX9GKo9IYT/fRFL6XUP/61iHzWRejDgcIVOY60vUlvH4+Zt8Hu8Tyq9y8QU5GiXR7pijYKgCynTJ+2yBl4ErVf2jdqx9VUWUcotABLiJcTD2jG4Y5t8WFZkOR68/x8WXQOFU/H1uiH1+wpUagRFtpAjoEPRy50qbuB/8hSgSFD0FfMXZXatJGwtPudKBb0JhBQZg49yRysVueg7QMLwqT9oK08GoubCoCdaizq3yNjprPR/WONJUgdN1tINbQ+gBV1rMsmYhsCPXNoRxTxOiEL7HFzeXRTMEQYfHGXbDC9KbmTaNxNpSMkteSeceGDlfZqjUTLRc27sv+GefBh6cOeZp9syAXnJ7aLBZUNHMBum2btmlvT2ggf15URufSlbJnsV2HZkeXWahwi6q8VFIVKQ="
