# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: React CI

on:
  push:
    branches: [ "main" ]

env:
  REACT_APP_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
  REACT_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
  REACT_APP_FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
  REACT_APP_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
  REACT_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
  REACT_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
  REACT_APP_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
  REACT_APP_FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
  GOOGLE_APPLICATION_CREDENTIALS: ${{ GITHUB_WORKSPACE }}/account.json

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - name: Build application
      run: npm run build
    - name: Generate production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build_${{ github.sha }}
        path: |
          build
          firebase.*
          .firebaserc
          firestore.*
        retention-days: 5
    # - run: npm test
    
  deploy:
    needs: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
      
    steps:
    - name: Download production artifacts
      uses: actions/download-artifact@v3
      with:
        name: build_${{ github.sha }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: echo $GITHUB_WORKSPACE
    - run: echo ${{ env.GITHUB_WORKSPACE }}
    - name: Install Firebase
      run: npm i -g firebase-tools
    - name: Create service account json
      run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > account.json
    - run: echo $GOOGLE_APPLICATION_CREDENTIALS
    - run: echo ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
    - name: Deploy
      run: firebase deploy --only hosting,firestore